### ISSUE TITLE
DWM Layout

### ISSUE THREAD

**Issue by kkharji** [starkwm/stark#18]
Hey @tombell, project looks really promising, javascript for configuration feels really empowering. I wonder if this project ready for testing.

Additionally, I'm a big fan of DWM layout and I wonder if this something I can help with implementing or it even if is considered within the scope of the project.

I currently use yabai, and I'm struggling to add DWM layout to it 😄 and that's when I stumbled on this awesome project.

Anyways, awesome work.

**Comment by tombell** [comment]
Thanks @tami5. Unfortunately Stark isn't meant to be a tiling window manager, just something I could use to easily position windows manually. The project is effectively in "maintenance mode" since I am working on something new for my needs.

I would stick with trying to get yabai working, or look at [Amethyst](https://github.com/ianyh/Amethyst).
